// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.AirQuality
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("pm2_5")]
        public double? Pm25 { get; set; }

        [JsonProperty("pm10")]
        public double? Pm10 { get; set; }

        [JsonProperty("carbonMonoxide")]
        public double? CarbonMonoxide { get; set; }

        [JsonProperty("ozone")]
        public long? Ozone { get; set; }

        [JsonProperty("nitrogenDioxide")]
        public double? NitrogenDioxide { get; set; }

        [JsonProperty("sulfurdioxide")]
        public double? Sulfurdioxide { get; set; }

        [JsonProperty("usEpaIndex")]
        public long? UsEpaIndex { get; set; }

        [JsonProperty("gbDefraIndex")]
        public long? GbDefraIndex { get; set; }

        [JsonProperty("recommendation")]
        public string Recommendation { get; set; }

        [JsonProperty("city")]
        public string City { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
